/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * anim.java
 *
 * Created on Jun 10, 2010, 10:18:12 AM
 */

package animation;
import javax.swing.Timer;
import java.awt.event.*;
import javax.swing.ImageIcon;

/**
 *
 * @author admin
 */
public class anim extends javax.swing.JFrame {

    /** Creates new form anim */
    public anim() {
        initComponents();}{
        Timer t=new Timer (200, new ActionListener() {
            public void actionPerformed(ActionEvent e){
                int i=Integer.parseInt(ctr.getText());
                int j=i%4;
                i++;
                ctr.setText(""+i);
                ctr.setVisible(false);
                switch(j){
                    case 0 : img.setIcon(new ImageIcon("E:\\Priyesh\\APPs\\CD11\\pics\\2.jpg"));
                    break;
                    case 1 : img.setIcon(new ImageIcon("E:\\Priyesh\\APPs\\CD11\\pics\\3.jpg"));
                    break;
                    case 2 : img.setIcon(new ImageIcon("E:\\Priyesh\\APPs\\CD11\\pics\\4.jpg"));
                    break;
                    case 3 : img.setIcon(new ImageIcon("E:\\Priyesh\\APPs\\CD11\\pics\\1.jpg"));
                    break;
                }
            }
    });
t.start();
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        ctr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        img.setIcon(new javax.swing.ImageIcon("E:\\Priyesh\\APPs\\CD11\\pics\\1.jpg")); // NOI18N

        ctr.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ctr, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ctr, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ctr;
    private javax.swing.JLabel img;
    private javax.swing.JLabel img1;
    // End of variables declaration//GEN-END:variables

}
