/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoanApp.java
 *
 * Created on Apr 17, 2010, 11:33:33 AM
 */

package hdfc;

/**
 *
 * @author admin
 */
public class LoanApp extends javax.swing.JFrame {

    /** Creates new form LoanApp */
    public LoanApp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField45 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField46 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextField56 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jTextField81 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField83 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jTextField84 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jTextField86 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jTextField87 = new javax.swing.JTextField();
        jTextField88 = new javax.swing.JTextField();
        jTextField89 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jTextField90 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HDFC Loan Application");
        setForeground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 18));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18));
        jLabel2.setText("Father's/Husband's Name");

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 18));
        jLabel3.setText("Current/Permanent*");

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 18));
        jLabel4.setText("Residential Address");

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18));
        jLabel5.setText("Current Residence Is");

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 24));
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("INDIVIDUAL LOAN APPLICATION FORM");

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 20));
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("PERSONAL AND EMPLOYMENT DETAILS");

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 14));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\admin\\My Documents\\250px-HDFC-Bank-logo.svg.png")); // NOI18N
        jLabel8.setText("With You, Right Through");

        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 12));
        jLabel9.setText("Surname");

        jLabel10.setFont(new java.awt.Font("Bell MT", 0, 12));
        jLabel10.setText("First Name");

        jLabel11.setFont(new java.awt.Font("Bell MT", 0, 12));
        jLabel11.setText("Middle Name");

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 18));
        jLabel12.setText("APPLICANT");

        jLabel13.setFont(new java.awt.Font("Bell MT", 1, 18));
        jLabel13.setText("CO-APPLICANT");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Bell MT", 0, 12));
        jLabel14.setText("Surname");

        jLabel15.setFont(new java.awt.Font("Bell MT", 0, 12));
        jLabel15.setText("First Name");

        jLabel16.setFont(new java.awt.Font("Bell MT", 0, 12));
        jLabel16.setText("Middle Name");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField8.addActi
