/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ncalc.java
 *
 * Created on Jun 6, 2010, 5:47:18 PM
 */

package forpkg;

/**
 *
 * @author admin
 */
public class ncalc extends javax.swing.JFrame {

    /** Creates new form ncalc */
    public ncalc() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cal = new javax.swing.JFrame();
        x = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        xn = new javax.swing.JTextField();
        y = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yn = new javax.swing.JTextField();
        so = new javax.swing.JButton();
        xy1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        xmy = new javax.swing.JTextField();
        xy2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        xuy = new javax.swing.JTextField();
        xy3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        xdy = new javax.swing.JTextField();
        xy6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sqry = new javax.swing.JTextField();
        xy5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sqrx = new javax.swing.JTextField();
        xy7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        yxp = new javax.swing.JTextField();
        xy = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        xyn = new javax.swing.JTextField();
        xy4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        xpy = new javax.swing.JTextField();
        xy8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        yxd = new javax.swing.JTextField();
        xy9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        yxs = new javax.swing.JTextField();
        id = new javax.swing.JPasswordField();
        word = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wtc = new javax.swing.JButton();
        ms = new javax.swing.JLabel();

        x.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        x.setText("x");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel6.setText("=");

        xn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xnActionPerformed(evt);
            }
        });

        y.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        y.setText("y");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel5.setText("=");

        yn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ynActionPerformed(evt);
            }
        });

        so.setText("SO");
        so.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soActionPerformed(evt);
            }
        });

        xy1.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        xy1.setText("x-y");

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel8.setText("=");

        xmy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xmyActionPerformed(evt);
            }
        });

        xy2.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        xy2.setText("x*y");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel9.setText("=");

        xuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuyActionPerformed(evt);
            }
        });

        xy3.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        xy3.setText("x/y");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel10.setText("=");

        xdy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xdyActionPerformed(evt);
            }
        });

        xy6.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        xy6.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\admin\\My Documents\\My Pictures\\sqrt.PNG")); // NOI18N
        xy6.setText("y");

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel13.setText("=");

        sqry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqryActionPerformed(evt);
            }
        });

        xy5.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        xy5.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\admin\\My Documents\\My Pictures\\sqrt.PNG")); // NOI18N
        xy5.setText("x");

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel12.setText("=");

        sqrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrxActionPerformed(evt);
            }
        });

        xy7.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        xy7.setText("y%x");

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel14.setText("=");

        yxp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yxpActionPerformed(evt);
            }
        });

        xy.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        xy.setText("x+y");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel7.setText("=");

        xyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xynActionPerformed(evt);
            }
        });

        xy4.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        xy4.setText("x%y");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel11.setText("=");

        xpy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpyActionPerformed(evt);
            }
        });

        xy8.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        xy8.setText("y/x");

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel15.setText("=");

        yxd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yxdActionPerformed(evt);
            }
        });

        xy9.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        xy9.setText("y-x");

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36));
        jLabel16.setText("=");

        yxs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yxsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calLayout = new javax.swing.GroupLayout(cal.getContentPane());
        cal.getContentPane().setLayout(calLayout);
        calLayout.setHorizontalGroup(
            calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
            .addGroup(calLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(xn, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yn, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(96, 96, 96))
            .addGroup(calLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(so)
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(calLayout.createSequentialGroup()
                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calLayout.createSequentialGroup()
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calLayout.createSequentialGroup()
                                .addComponent(xy1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xmy, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                            .addGroup(calLayout.createSequentialGroup()
                                .addComponent(xy2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xuy, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                            .addGroup(calLayout.createSequentialGroup()
                                .addComponent(xy3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xdy, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calLayout.createSequentialGroup()
                                .addComponent(xy6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sqry, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addGroup(calLayout.createSequentialGroup()
                                .addComponent(xy5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sqrx, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addGroup(calLayout.createSequentialGroup()
                                .addComponent(xy7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yxp, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
                    .addGroup(calLayout.createSequentialGroup()
                        .addComponent(xy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xyn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xy4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xpy, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(calLayout.createSequentialGroup()
                .addComponent(xy8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yxd, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xy9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yxs, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        calLayout.setVerticalGroup(
            calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
            .addGroup(calLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calLayout.createSequentialGroup()
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(so))
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calLayout.createSequentialGroup()
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xyn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(xy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xmy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(xy1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(xy2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xdy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(xy3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(calLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xpy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(xy4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yxp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(xy7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sqrx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(xy5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(xy6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(calLayout.createSequentialGroup()
                                .addComponent(sqry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yxd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(xy8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yxs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(xy9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setText("User ID");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel3.setText("Password");

        wtc.setText("Way To Calc");
        wtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wtcActionPerformed(evt);
            }
        });

        ms.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(word, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(wtc)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ms, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(wtc)
                .addGap(39, 39, 39)
                .addComponent(ms, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wtcActionPerformed
        // TODO add your handling code here:
        String uid=new String (id.getPassword());
        String code=new String (word.getPassword());
        if
        (uid.equalsIgnoreCase("priyesh")) {
         cal.setVisible(true);
         dispose();
        }
        else
            if
          (code.equalsIgnoreCase("210794")) {
         cal.setVisible(true);
         dispose();
        }
            else
                ms.setText("Check your id and password");
    }//GEN-LAST:event_wtcActionPerformed

        private void xnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xnActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_xnActionPerformed

        private void ynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ynActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_ynActionPerformed

        private void soActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soActionPerformed
            double xnn = Double.parseDouble(xn.getText());
            double ynn = Double.parseDouble(yn.getText());
            double xynnnn = xnn+ynn;
            xyn.setText(""+xynnnn);
            double xnm = Double.parseDouble(xn.getText());
            double ynm = Double.parseDouble(yn.getText());
            double xymm = xnm-ynm;
            xmy.setText(""+xymm);
            double xnu = Double.parseDouble(xn.getText());
            double ynu = Double.parseDouble(yn.getText());
            double xyuu = xnu*ynu;
            xuy.setText(""+xyuu);
            double xnd = Double.parseDouble(xn.getText());
            double ynd = Double.parseDouble(yn.getText());
            double xydd = xnd/ynd;
            xdy.setText(""+xydd);
            double xnp = Double.parseDouble(xn.getText());
            double ynp = Double.parseDouble(yn.getText());
            double xypp = xnp/ynp*100;
            xpy.setText(""+xypp);
            double n1=Double.parseDouble(xn.getText());
            double n12=Math.sqrt(n1);
            sqrx.setText(""+n12);
            double n2=Double.parseDouble(yn.getText());
            double n13=Math.sqrt(n2);
            sqry.setText(""+n13);
            double n3=Double.parseDouble(yn.getText());
            double n4=Double.parseDouble(xn.getText());
            double n34=n3/n4;
            yxd.setText(""+n34);
            double n5=Double.parseDouble(yn.getText());
            double n6=Double.parseDouble(xn.getText());
            double n56=n5-n6;
            yxs.setText(""+n56);
            double n8=Double.parseDouble(yn.getText());
            double n9=Double.parseDouble(xn.getText());
            double n89=n8/n9*100;
            yxp.setText(""+n89);
            // TODO add your handling code here:
}//GEN-LAST:event_soActionPerformed

        private void xmyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmyActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_xmyActionPerformed

        private void xuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuyActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_xuyActionPerformed

        private void xdyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xdyActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_xdyActionPerformed

        private void sqryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqryActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_sqryActionPerformed

        private void sqrxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrxActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_sqrxActionPerformed

        private void yxpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yxpActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_yxpActionPerformed

        private void xynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xynActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_xynActionPerformed

        private void xpyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpyActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_xpyActionPerformed

        private void yxdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yxdActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_yxdActionPerformed

        private void yxsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yxsActionPerformed
            // TODO add your handling code here:
}//GEN-LAST:event_yxsActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ncalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame cal;
    private javax.swing.JButton go;
    private javax.swing.JPasswordField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel ms;
    private javax.swing.JButton so;
    private javax.swing.JTextField sqrx;
    private javax.swing.JTextField sqry;
    private javax.swing.JPasswordField word;
    private javax.swing.JButton wtc;
    private javax.swing.JLabel x;
    private javax.swing.JTextField xdy;
    private javax.swing.JTextField xmy;
    private javax.swing.JTextField xn;
    private javax.swing.JTextField xpy;
    private javax.swing.JTextField xuy;
    private javax.swing.JLabel xy;
    private javax.swing.JLabel xy1;
    private javax.swing.JLabel xy2;
    private javax.swing.JLabel xy3;
    private javax.swing.JLabel xy4;
    private javax.swing.JLabel xy5;
    private javax.swing.JLabel xy6;
    private javax.swing.JLabel xy7;
    private javax.swing.JLabel xy8;
    private javax.swing.JLabel xy9;
    private javax.swing.JTextField xyn;
    private javax.swing.JLabel y;
    private javax.swing.JTextField yn;
    private javax.swing.JTextField yxd;
    private javax.swing.JTextField yxp;
    private javax.swing.JTextField yxs;
    // End of variables declaration//GEN-END:variables

}
