
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * stopwatch.java
 *
 * Created on Jun 4, 2010, 11:13:51 AM
 */

package stop;
import javax.swing.Timer ;
import java.awt.event.* ;

/**
 *
 * @author admin
 */
public class stopwatch extends javax.swing.JFrame {

    /** Creates new form stopwatch */
    public stopwatch() {
        initComponents();
        
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ho = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        se = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stopwatch");

        ho.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        ho.setText("0");

        jLabel2.setText(":");

        mi.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        mi.setText("0");

        jLabel4.setText(":");

        se.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        se.setText("0");

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 10));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\admin\\My Documents\\My Pictures\\copyrights.PNG")); // NOI18N
        jLabel3.setText("PV corporation Ltd.");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ho)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(mi)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(se))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addComponent(jButton2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ho)
                    .addComponent(jLabel2)
                    .addComponent(mi)
                    .addComponent(jLabel4)
                    .addComponent(se))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      Timer t = new Timer (1000, new ActionListener() {
       public void actionPerformed(ActionEvent e){
           int sec = Integer.parseInt(se.getText());
           int min = Integer.parseInt(mi.getText());
           int hou = Integer.parseInt(ho.getText());
           sec++ ;
           if (sec==60) {
               sec=0;
               min++;
               if (min==60){
                   min=0;
                   hou++;
                   if (hou==24) hou=0;
               }
           }

   se.setText(""+sec) ;
   mi.setText(""+min);
   ho.setText(""+hou);
   }
   });
   t.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stopwatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ho;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mi;
    private javax.swing.JLabel se;
    // End of variables declaration//GEN-END:variables

}
