/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * trigno.java
 *
 * Created on Apr 18, 2010, 7:47:40 PM
 */

package trigonometricfn;

/**
 *
 * @author admin
 */
public class trigno extends javax.swing.JFrame {

    /** Creates new form trigno */
    public trigno() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tanf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tana = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAN Calc");

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 24));
        jLabel1.setText("Tan");

        jButton1.setFont(new java.awt.Font("Bell MT", 1, 18));
        jButton1.setText("=");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 10));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\admin\\My Documents\\My Pictures\\copyrights.PNG")); // NOI18N
        jLabel2.setText("PV corporation Ltd.");

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 10)); // NOI18N
        jLabel3.setText("FOR ACUTE ANGLES ONLY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(tana, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tanf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(tana, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String tanfn=tanf.getText() ;
int tanfni=Integer.parseInt(tanfn);
double tanan=0;
switch (tanfni) {
    case 0 : tanan=.0000;
    break;
    case 1 : tanan=.0175;
    break;
    case 2 : tanan=.0349;
    break;
    case 3 : tanan=.0524;
    break;
    case 4 : tanan=.0699;
    break;
    case 5 : tanan=.0875;
    break;
    case 6 : tanan=.1051;
    break;
    case 7 : tanan=.1228;
    break;
    case 8 : tanan=.1405;
    break;
    case 9 : tanan=.1584;
    break;
    case 10 : tanan=.1763;
    break;
    case 11 : tanan=.1944;
    break;
    case 12 : tanan=.2126;
    break;
    case 13 : tanan=.2309;
    break;
    case 14 : tanan=.2493;
    break;
    case 15 : tanan=.2679;
    break;
    case 16 : tanan=.2867;
    break;
    case 17 : tanan=.3057;
    break;
    case 18 : tanan=.3249;
    break;
    case 19 : tanan=.3443;
    break;
    case 20 : tanan=.3640;
    break;
    case 21 : tanan=.3839;
    break;
    case 22 : tanan=.4040;
    break;
    case 23 : tanan=.4245;
    break;
    case 24 : tanan=.4452;
    break;
    case 25 : tanan=.4663;
    break;
    case 26 : tanan=.4877;
    break;
    case 27 : tanan=.5095;
    break;
    case 28 : tanan=.5317;
    break;
    case 29 : tanan=.5543;
    break;
    case 30 : tanan=.5774;
    break;
    case 31 : tanan=.6009;
    break;
    case 32 : tanan=.6249;
    break;
    case 33 : tanan=.6494;
    break;
    case 34 : tanan=.6745;
    break;
    case 35 : tanan=.7002;
    break;
    case 36 : tanan=.7265;
    break;
    case 37 : tanan=.7536;
    break;
    case 38 : tanan=.7813;
    break;
    case 39 : tanan=.8098;
    break;
    case 40 : tanan=.8391;
    break;
    case 41 : tanan=.8693;
    break;
    case 42 : tanan=.9004;
    break;
    case 43 : tanan=.9325;
    break;
    case 44 : tanan=.9657;
    break;
    case 45 : tanan=1.0000;
    break;
    case 46 : tanan=1.0355;
    break;
    case 47 : tanan=1.0724;
    break;
    case 48 : tanan=1.1106;
    break;
    case 49 : tanan=1.1504;
    break;
    case 50 : tanan=1.1918;
    break;
    case 51 : tanan=1.2349;
    break;
    case 52 : tanan=1.2799;
    break;
    case 53 : tanan=1.3270;
    break;
    case 54 : tanan=1.3764;
    break;
    case 55 : tanan=1.4281;
    break;
    case 56 : tanan=1.4826;
    break;
    case 57 : tanan=1.5399;
    break;
    case 58 : tanan=1.6003;
    break;
    case 59 : tanan=1.6643;
    break;
    case 60 : tanan=1.7321;
    break;
    case 61 : tanan=1.8040;
    break;
    case 62 : tanan=1.8807;
    break;
    case 63 : tanan=1.9626;
    break;
    case 64 : tanan=2.0503;
    break;
    case 65 : tanan=2.1445;
    break;
    case 66 : tanan=2.2460;
    break;
    case 67 : tanan=2.3559;
    break;
    case 68 : tanan=2.4751;
    break;
    case 69 : tanan=2.6051;
    break;
    case 70 : tanan=2.7475;
    break;
    case 71 : tanan=2.9042;
    break;
    case 72 : tanan=3.0777;
    break;
    case 73 : tanan=3.2709;
    break;
    case 74 : tanan=3.4874;
    break;
    case 75 : tanan=3.7321;
    break;
    case 76 : tanan=4.0108;
    break;
    case 77 : tanan=4.3315;
    break;
    case 78 : tanan=4.7046;
    break;
    case 79 : tanan=5.1446;
    break;
    case 80 : tanan=5.6713;
    break;
    case 81 : tanan=6.3138;
    break;
    case 82 : tanan=7.1154;
    break;
    case 83 : tanan=8.1443;
    break;
    case 84 : tanan=9.5144;
    break;
    case 85 : tanan=11.43;
    break;
    case 86 : tanan=14.30;
    break;
    case 87 : tanan=19.08;
    break;
    case 88 : tanan=28.64;
    break;
    case 89 : tanan=57.29;
    break;
    case 90 : tanan=0000000000000000000;
    break;

    
}
tana.setText(""+tanan);
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trigno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel tana;
    private javax.swing.JTextField tanf;
    // End of variables declaration//GEN-END:variables

}
